export const EVENTS = {
  TRANSACTION_ADDED: 'TRANSACTION_ADDED',
  ACCOUNT_ADDED: 'ACCOUNT_ADDED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  USER_UPDATED: 'USER_UPDATED',
  CATEGORIES_UPDATED: 'CATEGORIES_UPDATED',
};
